#!/usr/bin/env python
# encoding: utf-8
"""
Readme.py

Created by Hariharan Jayaram on 2009-01-28.
Copyright (c) 2009 __MyCompanyName__. All rights reserved.
"""

import sys
import os


def main():
	pass


if __name__ == '__main__':
	main()

